### ISSUE TITLE
Pronto Pago: ver desde Perfil Proveedor un ticket Ingresado y que está sin ppta por parte de Ingevec - Falta mensaje ERS 3.2.11.4

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#100]
1) Falta mensaje en Revisión, y no tiene ninguna info en pantalla (ej ver ticket 114 desde usuario cbastias)
2) Arriba de tabla cdice Fecha/hora POr que?
3) igual le debiera aparecer tabla con los documentos que solicito

![Image](https://user-images.githubusercontent.com/110253850/184192267-456e2770-c4db-4e53-a3f1-a00cf3f0b0bb.png)

**Comment by ManeAlessandri** [comment]
4) Tickets Sin propuesta comercial enviada, no debieran ver nada acerca de descuento comercial, monto a pago, fecha de pago , desglosa NC, etc. Lo unico que debieran ver es la tabla con los num documento, fecha y monto. Y una alerta de que está En revisión la solicitud

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
