### ISSUE TITLE
0 Crear Usuario Externo, con usuario ADMIN: problema al crear usuario externo (proveedor)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#104]
2 Problemas:
1) Cree usuario Externo (Proveedor) para mail ricardoalessandrim@gmail.com (Nombre: Proveedor_RAM y Apellido: Prueba desde ADMIN) desde Admin con usuario admin@spsgroup.cl. Estuve monitoreando el correo para ver si llegaba confirmación al usuario y clave para poder entrar, han pasado 15 min y no ha llegado correo a usuario para poder acceder.
Yo estaba super pendiente, para poder probar acceso porque usuario se crea sin clave.

2) Mi sorpresa es que cuando me cambio de pestaña desde Github, de vuelta al portal con mi usuario Admin abierto, me parece que estoy conectado como el usuario proveedor recien creado (y yo no tengo como haber conseguido la clave para haber ingresado). Adjunto pantallazo:

![Image](https://user-images.githubusercontent.com/110253850/185214291-92c95c7a-35f9-4ab8-8d01-63d0baa4aff7.png)

**Comment by ManeAlessandri** [comment]
URGENTE NIvel 0

**Comment by Ditassara** [comment]
1. Lo revisé y el correo se demora en llegar un par de minutos, llega con contraseña.
2. No me ocurrido nada similar, probé recargando la página, cambiando entre módulos y no he tenido ningún problema.

**Comment by ManeAlessandri** [comment]
ok
