### ISSUE TITLE
0 Tickets Activos y Cerrados con Proveedor en Blanco o con proveedor CONSTRUCTORA INGEVEC 2 hay problemas

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#105]
1) Problema con proveedor en blanco en lista de activos y cerrados
2) Proveedor 1-9 "CONSTRUCTORA INGEVEC 2" hay problema con nombre que aparece duplicado en filtro de busqueda de tablas de activos y cerrados

**Comment by ManeAlessandri** [comment]
0 Urgente: este error que o puede estar en productivo

**Comment by Ditassara** [comment]
En cerrados sigue apareciendo proveedor en blanco en el filtro.

**Comment by ManeAlessandri** [comment]
ok
