### ISSUE TITLE
OK PROD 2 Ver TIcket Pronto Pago: filtros en tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#109]
Ajustar al siguiente formato, dependiente de perfil:

Ingevec (administrador y Pago Proveedor):
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA
-- | --
Nivel Criticidad | Lista deplegable y   sin busqueda (solo selección)
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto)
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos
Rut Proveedor | Búsqueda en formato   con puntos y -, lista desplegable ABC
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Estado | Lista deplegable y   sin busqueda (solo selección)

</body>

</html>

Perfil Proveedor:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA
-- | --
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto)
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Estado | Lista deplegable y   sin busqueda (solo selección)

</body>

</html>

**Comment by Ditassara** [comment]
Esto según ERS no estaría considerado y la prioridad actualmente es pasar al productivo, por lo tanto quedaría como mejora a futuro y considerado un adicional.

**Comment by ManeAlessandri** [comment]
Perfiles Ingevec:
ID Ticket: Pdte orden ABC
Rut/Proveedor/Creado por / Gestionado Por --> No tengo como probarlos porque tiene un solo valor en lista desplegable (además de vacio)

Fecha Creación: se requiere rango (porque no hay más fechas ni cabecera para buscar )
Se pasa a Todo 2

**Comment by matiaskatsh** [comment]
pdte:fecha

**Comment by matiaskatsh** [comment]
resuelto

**Comment by ManeAlessandri** [comment]
ok
