### ISSUE TITLE
Falta botón volver atrás

### ISSUE THREAD

**Issue by Ditassara** [matiaskatsh/front_integracion#11]
Falta botón volver atrás en estadísticas de tickets.

![Image](https://user-images.githubusercontent.com/56659426/179277755-04d2ca05-4d5f-445a-a175-91cfc0b64894.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok

**Comment by ManeAlessandri** [comment]
no me deja cerrar
