### ISSUE TITLE
2 Modulo Gestionar Proveedor: Filtros de tabla (1 error)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#110]
En los filtros de tabla de gestionar proveedores hay 1 solo error: Lista desplegable de Rut no está en orden ABC o de menor a mayor

Todo el resto esta ok:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA
-- | --
Rut Proveedor | Búsqueda en formato con puntos y -,   lista desplegable ABC
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Nivel de   Criticidad | Lista deplegable ABC,   selección multiple y sin busqueda (solo selección)
Pronto Pago | Checkbox: Habilitado   / No habilitado

</body>

</html>

**Comment by Ditassara** [comment]
El filtro funciona sin problemas, el rut que aparece de 17.304.049-0 al ordenar de forma descendente, aparece antes por dato incorrecto en base de datos.


![Image](https://user-images.githubusercontent.com/56659426/185697616-2ceffb44-9b2b-4df8-8a7e-52fb1832535f.png)

**Comment by ManeAlessandri** [comment]
Filtro de Habilitado No Habilitado, no está funcionando para "No Habilitado". Se devuelve a Todo

**Comment by Ditassara** [comment]
Resuelto.

**Comment by ManeAlessandri** [comment]
Este mismo Usuario, no me deja deshabilitar usuario Ticket 145 (2 Todo)

**Comment by ManeAlessandri** [comment]
ok
