### ISSUE TITLE
0 Carga Masiva Proveedores: No funciona, no genera alertas, Revisar ERS 3.2.12.2 completo

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#112]
De solo comenzar comienzan los errores con la carga masiva, algunos de los pocos detecetados:
1) Veta de carga de archivo no se coerra y boton de ajuntar archivo no está abajo a la derecha (ticket 111)

Lo demás sin tickets:
2) Permite modificar Criticidad y PP solo de rut 1-9, probé con 3 distintos, usando los 10 dígitos como dicen las instrucciones y nada
3) Si cargo archivo CSV en blanco, tal como descargue palntilla, me dice carga exitosa.
4) Cambio de criticidad: (solo con rut 1-9) acepta Alto o Alta, Medio o Media, sin importar mayúsculas, pero no hay forma de que acepte cambio a Estándar o Estandar o Bajo --> ACEPTA SOLO CON "BAJA"
5) no arroja ningun tipo de error en formatos de campos, o archivos vacios o Rut inexistentes

   Chequear todo el detalle de ERS antes de psar a QA, o al menos todo lo siguiente:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Permite   carga de criticipadad y PP, en formato CSV
--
Está   plantilla disponible?
Carga   con archivo vacio
Excel   exige al menos 1 proveedor
Formato   de RUT de carga? Viene especificada en CSV
Formato   RUT 10 digitos sin puntos ni guion, funciona?
Rut en   formato errado, con guion , que pasa? Mensaje?
Rut en   formato errado, 9 digitos, que pasa?Mensaje?
Rut en   formato errado, 11 digitos, que pasa?Mensaje?
Rut en   formato errado, con puntos , que pasa?Mensaje?
Nombre:   carga es opcional? Funciona en blanco y con dato
Nombre:   que pasa si cargo nombre distinto al que hay en sistema, cual se respeta?
Nombre:   nombre distinto arroja error?Mensaje?
Criticidad:   formato "Alto", "Medio"    o "Estandar"
Criticidad:   qué pasa con formato errado: probar Alta, alta, Media, media, medio, Bajo,   Estándar, estandar, estándar. Mensaje?
PP: true   o false, funciona?
PP: que   pasa con True, False, Verdadero, Falso, Habilitado y No Habilitado, 1 o 0.   Mensaje?
Si   sistema detecta Rut no registrado, detiene operación? Probar con rut de 10   digitos no registrado. Mensaje?
Se   reflejan cambios en tabla? Como? Cirticidad y PP, solo Criticidad y solo PP
Probar 1   carga con: 1 proveedor con nueva criticidad y nuevo PP, 1 proveedor con misma   criticidad y mismo PP, 1 proveedor con nueva criticidad y blanco PP, 1   proveedor con blanco criticidad y nueva PP, 1 proveedor con ambos en blanco:   Como se refleja en tabla
Probar   con proveedores, efecto de cambio de criticidad y efecto cambio PP,  tickets que no eran PP ahora si aparecen, y   viceversa?

</body>

</html>

**Comment by ManeAlessandri** [comment]
0 Urgente: parte de ERS y con muchas funcionalidades y pruebas por validar pendientes una vez que se resuelva

**Comment by cbastiasv** [comment]
Resuelto. (Se eliminó la columna NOMBRE)

**Comment by Ditassara** [comment]
No me dejó cargar el archivo, a pesar de que los datos eran correctos.

Esto es lo que me devolvió.
![Image](https://user-images.githubusercontent.com/56659426/186777722-49993348-2186-4798-89d6-2cc7e8c7e9ab.png)
Datos que se ingresaron
![Image](https://user-images.githubusercontent.com/56659426/186777920-12a3845e-1da5-44d5-bcf0-1b3e099eff24.png)
Instrucciones del archivo
![Image](https://user-images.githubusercontent.com/56659426/186778027-4d886c4f-270f-4da6-b44f-41f4a4fae5de.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok, resuleto completo
