### ISSUE TITLE
1 Cambio Criticidad Proveedor 3.2.12.3: No está de acuerdo a ERS

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#113]
ERS indica:

![Image](https://user-images.githubusercontent.com/110253850/185443053-69b651bd-a509-443a-9f20-a2c6732ffd37.png)

El cambio no se esta produciendo retroactivo, sino que solo en los tickets creados posteriormente.

Notar que en el caso de cambiar a criticidad estandar,  corre solo la criticidad del tipo de ticket. No es necesario comparar criticidad proveedor vs tipo de ticket

**Comment by ManeAlessandri** [comment]
1 Urgente: parte importante del ERS, permite dar prioridad a un proveedor en forma urgente

**Comment by Ditassara** [comment]
Funciona, hace el cambio, tiene una pequeña demora, pero lo hace.

**Comment by ManeAlessandri** [comment]
ok, se deja registro que cambio de criticidad por tipo de tickets no es retroactiva (esto porque no esta mencionado en ERS)
