### ISSUE TITLE
Tablas Activos / Cerrados y Pronto Pago ERS 3.2.9: problema en excel descargados

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#118]
Excel descargado vienen sin columna criticidad, y tampoco viene con campos de fechas completados. Al menos en Activos y Cerrados. Pronto Pago no puedo Chequear a la espera de Ticket 117. Cheuquear uds las 3 descargas, desdde los 3 perfiles.

![Image](https://user-images.githubusercontent.com/110253850/185463798-29d43cfa-6389-4dff-b30d-fa1a8c9a6de3.png)

**Comment by Ditassara** [comment]
Corregido, solamente en Cerrados no se incluye columna criticidad, ya que la tabla no trae dicha columna.

**Comment by ManeAlessandri** [comment]
ok
