### ISSUE TITLE
2 Modulo Datos Proveedor: (solo perfil Proveedor) problema en modificacion de datos de Pago

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#121]
Permite cambiar a Vale Vista, da mensaje de cambio guardado, pero cuando uno vuelve a entrar a modulo, sigue diciendo cheque (Usuario cbastias@spsgroup.cl Prov 1-9)

![Image](https://user-images.githubusercontent.com/110253850/185470333-553d9d0e-d8fa-4176-9d4b-a6614a228f61.png)

Si quiero poner cuenta Cte: no están los bancos cargados y no me deja guardar. Tampoco se si valida que RUT de cta cte coincida con Rut proveedor.

Corregir todo y chequear que esté funcionando al 100%

**Comment by ManeAlessandri** [comment]
Sigue 1 problema, hay solo 2 bancos para Cta Cte: de todos modos no es relevante, **queda en 2 Todo**


![Image](https://user-images.githubusercontent.com/110253850/186675263-7172ad9f-355e-40a7-b4fb-7df96d86a0f9.png)

**Comment by matiaskatsh** [comment]
Los bancos deben ser ingresados por Ingevec.

**Comment by ManeAlessandri** [comment]
Perfecto, necesito el mantenedor habilitado o bien que el campo sea de texto abierto

**Comment by ManeAlessandri** [comment]
Estimados:
Agregar Banco Security (faltó)
Sacar Coopeuch, ercado Pago y Tenpo Prepago

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
