### ISSUE TITLE
1 Ampliar Vistas de todos los módulos segun ERS ( Usuarios, Gestionar Proveedores y Tickets está resuelto)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#125]
Ampliar vista en TODOS los perfiles en los siguientes módulos como en prototipos de ERS:
- Inicio
- Cuenta Corriente
- Ver Lote
- Pagos
- Órdenes de Compra
- Estadísticas Portal
- Datos del Proveedor 
- Solicitudes de Creación de Usuarios

Vistas correctas:

![Image](https://user-images.githubusercontent.com/110253850/186167487-dcb07b63-b31a-4168-bf7e-31f3d9ac92d3.png)

Vistas a corregir:

![Image](https://user-images.githubusercontent.com/110253850/186167579-4542a46d-7517-4421-8d5d-d8525c0f6364.png)

**Comment by Ditassara** [comment]
Resuelto.

**Comment by ManeAlessandri** [comment]
ok
