### ISSUE TITLE
1 AL FINAL Carga Inicial de Datos en Modulos: para perfiles Ingevec Suspender

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#126]
La carga inicial estaba con 6 meses, pero dado los tiempos que toma, se solicita no cargar datos SOLO a usuarios Ingevec en los Módulos: Cuenta Corriente, Pagos y Órdenes de Compra

Chequear:
1) que quede ok (sin carga) para perfiles Administrador y Pago Proveedor.
2) Con carga para Perfiles Proveedor

**Comment by Ditassara** [comment]
Resuelto.

**Comment by ManeAlessandri** [comment]
ok
