### ISSUE TITLE
PARA PROD 1 Ajustar lo más posible los campos de todas las tablas (mayor visualización) de acuerdo a prototipos ERS - RESOLVER ESTE TICKET DESPUES DEL 129

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#128]
RESOLVER DESPUÉS DE TICKET 129 (porque generará ajustes)
Achicar ancho de campos, para mayor visualización de una vez y sin scroll o el mínimo posible:
Módulos:
- Usuario: 
   - Interno OK
   - Externo PDTE
   - Solicitudes de Creación de Usuarios PDTE
 - Gestionar Proveedores OK
 - Cuenta Corriente: PDTE
 - Pagos:
    - Pantalla inicial PDTE
    - Ver Lote PDTE
- Órdenes de Compra PDTE
- Tickets:
   - Activos PDTE
   - Cerrados PDTE
   - Pronto Pago PDTE
- Estadísticas del Portal: no aplica por no tener columnas, cuando esten resueltos los tickets asociados se verá el tema de visualización

**Comment by Ditassara** [comment]
En espera de ticket 129.

**Comment by ManeAlessandri** [comment]
se mando a QA sin haber tenido ningun avance

**Comment by ManeAlessandri** [comment]
Módulos:
- Tickets: **Ok excelente solución** fijando a la derecha los botones
   - Activos 
   - Cerrados 
   - Pronto Pago 
- Usuario: 
   - Interno 
- Gestionar Proveedores

NO resuelto
- Usuario: 
   - Externo PDTE
   - Solicitudes de Creación de Usuarios PDTE
 - Cuenta Corriente: PDTE no está ajustado ningún campo (ejemplo: Rut Proveedor, Grupo, Compañía, Obra, Tipo, etc etc). Desaparecio boton para crear ticket (abrire otro ticket en Github)
 - Pagos:
    - Pantalla inicial PDTE habiamos conversado de dejarlo igual que ticket, con el botón de abrir ticket fijo a la derecha
    - Ver Lote PDTE ajustar un minimo algun campo y cabe todo, o ampliar ventana desplegable
- Órdenes de Compra PDTE idem a cuenta corriente en cuanto a vista. Desaparecio boton para crear ticket (abrire otro ticket en Github)

- Estadísticas del Portal: no aplica por no tener columnas, cuando esten resueltos los tickets asociados se verá el tema de visualización

**Comment by ManeAlessandri** [comment]
OK
