### ISSUE TITLE
Configuración Tiempos SLA

### ISSUE THREAD

**Issue by Ditassara** [matiaskatsh/front_integracion#13]
Permite configurar y guardar tiempos negativos en SLA.

![Image](https://user-images.githubusercontent.com/56659426/179282139-a900e6e7-533a-4529-baae-dd4ee3472d72.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
No deja numeros negativos porque se bloquea boton guardar, pero no da alerta

**Comment by matiaskatsh** [comment]
Resuelto
