### ISSUE TITLE
2 Mensaje fuera de horario: error, entrega mensaje estando dentro de horario

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#130]
Me paso con el 223, 224 y 225 (todos los tickets) fueron creados por proveedor desde vista de tickets para crear tickets

![Image](https://user-images.githubusercontent.com/110253850/186226950-919f73c0-6a61-439e-b410-c3dc0ac3ec87.png)

**Comment by Ditassara** [comment]
Resuelto, lo probé con los tickets 286 y 287, creados con proveedores distintos.

**Comment by ManeAlessandri** [comment]
ok
