### ISSUE TITLE
000 URGENTISIMO: Ver Lote de pago no esta filtrando por rut de proveedor

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#131]
Ver Lote de Pago, esta mostrando lote de pago completo. O sea si Ingevec Hizo un lote de pago de 1.500MM a todos sus proveedores  y solo 2MM era para el proveedor XX --> el portal actualmente al proveedor XX cuando visualiza el lote de pago, le muestra todo el detalle de los 1.500MM incluso con los PDF de las facturas de los demas proveedores.

Ver Lote de pago TIENE que estar filtrado por Rut de Proveedor (desde todos los perfiles)

**Comment by ManeAlessandri** [comment]
![Image](https://user-images.githubusercontent.com/110253850/186507065-93b449e4-d377-410d-9059-673350307b6b.png)

**Comment by ManeAlessandri** [comment]
SOLO en RUT 1-9 parece estar resuelto, pero cuando miro detalle de Lote 0380975 por $924.000, me aparecen 2 pagos (proveedor no tienen mas pagos por ese monto (tabla filtrada por monto)

![Image](https://user-images.githubusercontent.com/110253850/186728612-bcebfb8f-b59d-4b4d-a7b9-2b7a0e374ad7.png)

### PROBLEMA PERSISTE EN LOS DEMAS PROVEEDORES
Aparte de RUT 1-9, con todos los otros RUT que busque problema no esta resuelto (91.361.000-8, 78.817.860-3 y 76.005.814-9) PROBLEMA PERSISTE (veo lotes completos de pago y no los movimientos exclusivos de ese proveedor)

**Comment by matiaskatsh** [comment]
![Image](https://user-images.githubusercontent.com/74660636/186750948-b3dee101-f757-4cc9-8bfd-b1ef6975d62f.png)

**Comment by matiaskatsh** [comment]
El lote de pago consta de 2 registros para el rut 1-9

**Comment by Ditassara** [comment]
Revisé que el rut del proveedor coincidiera con el rut que aparece en el lote de pago y no he encontrado alguno que no coincida.
Revisé los rut 76.792.892-0, 76.899.687-3, 76.320.186-4, 77.058.339-K, 10.179.789-9, 76.266.331-7, 76.691.149-8.

**Comment by ManeAlessandri** [comment]
ok
