### ISSUE TITLE
OK PROD 2 Tablas de archivos adjuntos en ticktes: están ordenados por nombre que adjunto y no por fecha

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#132]
Incluso entre la misma persona que los cargo, estan desordenados por fecha. Ideal que este solo ordenado por fecha y hora

![Image](https://user-images.githubusercontent.com/110253850/186531779-efede2f7-3321-4a6d-b21e-47c4d4b92226.png)

**Comment by matiaskatsh** [comment]
No se puede ordenar por fecha de subida, los archivos son muy pesados y deben descargarse de manera asincrónica, esto no nos permite ordenarlos

**Comment by ManeAlessandri** [comment]
ok, al menos quedan ordenados por hora de quien lo adjunto
