### ISSUE TITLE
0 Ver Tickets Pronto Pago: Ticket 244 duplicado (lo acabo de crear)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#134]
Cree ticket Pronto Pago 244, desde proveedor cbastias, luego en administrador (admin admin) visualizo los tickets Pronto pago y el 244 aparece duplicado y ambos en estado "Ingresado".

Accedo a uno de ellos para ver si pasa a estado en revisión y si asigna al "gestionado por", ambas cosas ocurren pero solo en el caso de la primera fila, la ultima se mantiene como estaba:
Esto se mantiene incluso saliendo del modulo

![Image](https://user-images.githubusercontent.com/110253850/186534495-9142dd9c-33ed-4935-98fa-44e7d2902260.png)

![Image](https://user-images.githubusercontent.com/110253850/186534558-83531d15-fa51-4e7e-8ea7-9e21adba3121.png)

**Comment by Ditassara** [comment]
Resuelto, lo probé creando un ticket nuevo, el 290 desde proveedor cbastias.

**Comment by ManeAlessandri** [comment]
lok
