### ISSUE TITLE
2 Tabla Pronto Pago en Modulo Inicio (perfil Proveedores) : cambio de campos (ERS 3.2.11.1)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#135]
Portal esta como ERS, pero los campos de la tabla no son utiles para proveedor.

![Image](https://user-images.githubusercontent.com/110253850/186677799-ac02ad88-11fb-4d48-92c4-3adb2883229b.png)

Se solicita cambiar a los mismos campos del mensaje de Ingresar Solicitud Pronto Pago, incluyendo al comienzo la columna para checkbox de selección : CheckBox / Numero de Documento / Fecha de Documento / Monto **(con símbolo $)**

![Image](https://user-images.githubusercontent.com/110253850/186678219-36dda052-050a-4073-88e7-d150bd0ba7aa.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
