### ISSUE TITLE
2 Enviar Solicitud de Pronto Pago: mensaje de confirmación: cuando hay muchos documentos scroll vertical, está con hojas (ERS 3.2.11.2)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#137]
![Image](https://user-images.githubusercontent.com/110253850/186680155-e3761d8c-074a-423c-9efb-293fe3296db1.png)

![Image](https://user-images.githubusercontent.com/110253850/186680233-65c0644c-875e-476f-928a-55b07fae71d9.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok  resuelto
