### ISSUE TITLE
2 Total en Mensaje confirmación Pronto Pago (ERS 3.2.11.2), no está total

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#138]
ERS:

![Image](https://user-images.githubusercontent.com/110253850/186680770-29042811-1ef3-4846-9463-8727ca609bb8.png)

POrtal:

![Image](https://user-images.githubusercontent.com/110253850/186680819-07cefa70-00ef-411f-a67f-fb8b96690744.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
