### ISSUE TITLE
2 Gestionar Proveedores: 1 proveedor no se puede deshabilitar de pronto pago

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#145]
![Image](https://user-images.githubusercontent.com/110253850/186997151-ecd8290d-0036-4d27-9864-dcc8d734ab1a.png)

**Comment by ManeAlessandri** [comment]
Acabo de notar que esta en pre QA, ojo que proveedor ya no existe por nombre ni rut

**Comment by Ditassara** [comment]
Resuelto, se eliminó proveedor ya que no cumplía con formato al estar creado en duro.

**Comment by ManeAlessandri** [comment]
ok
