### ISSUE TITLE
OK PROD 000 Urgentísimo: Cta Cte consulta no esta entregando registros correctos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#148]
Cta  Ctae, estaba chequeando con portal actual, para verificar los registros y no coincide:
ejemplo considerado: RUT 93933000-3 fechas entre 01/07/22 y 10/07/22

Portal Nuevo: 5 registros

![Image](https://user-images.githubusercontent.com/110253850/187247855-1b345a25-6f99-4037-951c-f82c94973389.png)

Portal Antiguo: 15 registros:

![Image](https://user-images.githubusercontent.com/110253850/187247972-4fd6d932-f7c6-4e9c-988b-8fb31ebc15f3.png)

Consulta a la BBDD: 15 registros (los mismo que portal antiguo

**Comment by matiaskatsh** [comment]
Resuelto (Confirmar data en productivo)

**Comment by ManeAlessandri** [comment]
Estimados hay un error en el filtro  facturas pagadas --> setoy validando internamente, cuales serían todas la condiciones para identificar un documento como pagado... pero al menos debiera ser saldo en $0, no necesariamente que tenga un lote de pago (ejemplo documentos 46008 y 10511121 de 93.933.000-3)

**Comment by ManeAlessandri** [comment]
Estimados: Confirmado, documento pagado es aquel con Saldo $0, sin importar estado del documetno ni #Lote Pago

Por favor corregir filtro

**Comment by Ditassara** [comment]
Resuelto.

**Comment by ManeAlessandri** [comment]
OK
