### ISSUE TITLE
000 Urgentisimo: Modulo Pagos tampoco cuadra con datos BBDD y portal Antiguo

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#149]
![Image](https://user-images.githubusercontent.com/110253850/187248875-8ec72392-fd9f-49e2-b721-4a4759dc4e26.png)

![Image](https://user-images.githubusercontent.com/110253850/187248923-57cb895e-5b0a-46d7-a7f8-9ca831fb80a9.png)

**Comment by matiaskatsh** [comment]
Resuelto (Confirmar data en productivo)

**Comment by ManeAlessandri** [comment]
ok
