### ISSUE TITLE
PARA PROD Ver Tickets Pronto Pago (perfil Ingevec): no sé en qué orden está la tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#153]
En los Tickets Pronto Pago, agrego uno nuevo (#292) y me aparecio en 3er lugar con Perfil Ingevec (no por numero de ticket, ni por fecha creación. Para Proveedor, me quedó primero

![Image](https://user-images.githubusercontent.com/110253850/187801044-e2b95477-d9b3-4af7-af7c-0cfe14095261.png)

La vista del Proveedor:

![Image](https://user-images.githubusercontent.com/110253850/187801100-48ba7b32-9a8a-464d-8deb-6d30a1934bb9.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Estan ordenados en perfil proveedor, pero no tengo documentos para probar la creación de un nuevo ticket - PDTE

**Comment by ManeAlessandri** [comment]
ok productivo
