### ISSUE TITLE
OK PROD Carga de Portal Productivo: Excesiva demora en cargar todos los filtros de búsqueda

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#154]
Este problema no esta ocurriendo en Test.

Al inspeccionar la carga de la pagina web
El problema se presenta en todos los 3 perfiles:
1) Al ingresar al portal se demora en cargar las listas desplegables de búsqueda de cabecera de todos los módulos. Inspección de web tiene una partida que demora **46seg**, probado en 2 computadores con distinto internet.

![Image](https://user-images.githubusercontent.com/110253850/188194963-dddad1c2-34fa-4a76-b40a-cab3e45cc7bc.png)

Apretando flecha hacia abajo:
![Image](https://user-images.githubusercontent.com/110253850/188195004-56b3f18f-aa0c-49bf-8074-7d1f86b87545.png)

2) Al hacer refresh, estando dentro del modulo, tambien se demora en cargar, al inspeccionar hay una llamada que se demora alrededor de 7seg, cuando todas las demás se demoras ms.

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok, pero a la espera de carga completa de documentos para terminar de probar

**Comment by ManeAlessandri** [comment]
ok
