### ISSUE TITLE
Modulo Cuenta Cte: Campo Observaciones está en blanco en todos los casos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#156]
Campo Observaciones viene vacio, hay que mantener el tutulo, pero completar los datos con campo "DetalleNCsolicitada" o "RespaldoNCsolicitada" que son iguales

IMPORTANTE: tener mucho cuidado con el formato, porque es un campo de mucho texto en algunos casos (más de 500 caracteres y en promedio 100), si se puede ver una parte y luego presionar para visualizar todo (así no afecta al diseño de  la tabla)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
