### ISSUE TITLE
Formulario para crear Nuevo Usuario Interno perfil "Pago Proveedor" No Funciona (ERS 3.2.4.3 Crear nuevo usuario Interno) --> Resuelto: ahora problema con multiples mensajes

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#17]
Devuelto a todo: se corrigió el problema de creación de nuevo Usuario Interno, pero en la pruebas usé correo malessandri@miuandes.cl y manealessandri@gmail.com, que quedaron creados como usuarios. Pero no aparecen en listado de usuarios Interno y tampoco me permite crearlos de nuevo.

Pantallazos:

![Image](https://user-images.githubusercontent.com/110253850/182695048-738f35de-f498-4d40-8dda-66357a215ee0.png)

![Image](https://user-images.githubusercontent.com/110253850/182695063-252771d5-de6c-40ca-ae91-5bf7f112464d.png)

Completo los datos para nuevo usuario

![Image](https://user-images.githubusercontent.com/110253850/182496209-7690f9e9-c3b6-43d4-9a70-6b803744b061.png)

Al hacer click en "Agregar Usuario" no pasa nada, se mantiene la misma pantalla

![Image](https://user-images.githubusercontent.com/110253850/182496246-3a1444f6-da4d-4f10-8117-bdb65b1aeb73.png)

Al hacer click por 2da vez en "Agregar Usuario" me aparece mensaje de email ya registrado

![Image](https://user-images.githubusercontent.com/110253850/182496279-b3fc4fc0-732f-4e3a-b4c5-ff0532beb65c.png)

Presiono cancelar y Voy a chequear si el usuario me aparece en lista de Usuarios Internos y no está en listado

![Image](https://user-images.githubusercontent.com/110253850/182496329-372b5da6-db1c-423a-bf58-5892f7ccd918.png)

**Comment by cbastiasv** [comment]
Corregido, en Repositorio

**Comment by ManeAlessandri** [comment]
Ahora se pueden crear, pero me arroja una serie de mensajes, que no debieran tener relación ni menos ser tantos, entre Ellos los siguientes: (me avisan si queda en este ticket i hago otro?


![Image](https://user-images.githubusercontent.com/110253850/183658834-f653eaa1-9559-4679-94d8-6b6db4366283.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
