### ISSUE TITLE
Formulario en Inicio página web para crear nuevo Proveedor está con error en formato de RUT y no deja crear (máximo 9MM el RUT ) --> ERS Crear Usuario Perfil Proveedor 3.2.3.

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#18]
![Image](https://user-images.githubusercontent.com/110253850/182465875-54d0a765-85dc-4ece-bdf2-25da903fd9a5.png)

**Comment by cbastiasv** [comment]
Corregido RUT. Aun no está implementado el envío de correos electrónicos por lo que no permite crear usuarios mediante esta vía

**Comment by ManeAlessandri** [comment]
Corregido error de Rut, pero boton "crear usuario" está deshabilitado, es por cantidad de caracteres de RUT

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
