### ISSUE TITLE
Modificar Datos Usuario Externo, en Modulo Gestionar Usuarios (ERS 3.2.4.6): no se puede, error de RUT no registrado

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#19]
No permite modificar datos (apellido en ejemplo) porque dice que RUT no está registrado en sistema

![Image](https://user-images.githubusercontent.com/110253850/182708960-ad851475-7438-42b3-b8e2-7bad4ebd0e18.png)

**Comment by cbastiasv** [comment]
Corregido, en Repositorio

**Comment by ManeAlessandri** [comment]
Ok, se pueden corregir los 3 campos Nombre, apellido y rut (siempre y cuando este registrado)
