### ISSUE TITLE
Perfil Pago Proveedor: hay un problema de definición del nombre

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#20]
Perfil Pago Proveedor, habia 1 usuario creado antes de que yo creara otro (desde perfil admin Admin). El usuario original es Matias Fuentes con mail pagoproveedor@spsgroup.cl y que yo cree es Admin_1 Prueba 1 mail malessandri@ingevec.cl.
Mi usuario lo cree primero con perfil Administrador y luego lo cambie a perfil "Pago Proveedor"

El problema está en que en listado de Usuarios Internos aparecen estos 2 usuarios perfil Pago Proveedor, pero no descripción del perfil distinto: Matías está como Pago_Proveedor y Admin_1 está como "Pago Proveedor" (sin _)

![Image](https://user-images.githubusercontent.com/110253850/182920729-20c918f1-120c-485c-91b2-bf429c8d3283.png)

No sé si el problema en el nombre del perfil, estará en el creado originalmente (Matías) o en el cambio de tipo de perfil. Pero al momento de filtrar por perfil en la tabla aparece solo: "Administrador" y "Pago Proveedor". Si elijo "Pago Proveedor" esperaría que quedara solo el perfil de Admin_1, pero queda Matías (a pesar de que tiene "_")

![Image](https://user-images.githubusercontent.com/110253850/182921227-1bfd9af0-a663-41c5-b8c3-7d22c5ff102f.png)

![Image](https://user-images.githubusercontent.com/110253850/182921316-a86cbe53-cd5d-45d2-9735-f045236c5c70.png)

**Comment by cbastiasv** [comment]
Corregido, en Repositorio

**Comment by ManeAlessandri** [comment]
ok
