### ISSUE TITLE
Mejora en filtros de tabla Usuario Internos/ Externos en Módulo Usuarios (ERS 3.2.4.11) --> Falta corrección en selecciones múltiples

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#21]
1) Tabla de Usuarios Internos:
Filtros de campos: corregir de acuerdo a tabla. Filtros de campos Perfil y Estado están ok, los demás requieren mejoras
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Usuarios   Internos | Perfil | Lista   deplegable ABC, selección multiple y contiene (no exacto) | ok
-- | -- | -- | --
Usuarios   Internos | Nombre | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Usuarios   Internos | Apellido | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Usuarios   Internos | Email | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Usuarios   Internos | Estado | Checkbox: habilitado   / No habilitado | ok

</body>

</html>

2) Tabla Usuarios Externos:
   i) No se puede verificar si existe el mismo error que en internos, puesto que hay solo 2 registros y están por ABC (no sé si por coincidencia). No puedo crear más proveedores (hasta corregir error en RUT. Por favor chequear que los filtros estén configurados como en la siguiente tabla:
Pude identificar que Nombre Proveedor necesita corrección
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Usuarios   Externos | Rut Proveedor | Búsqueda en   formato con puntos y -, lista desplegable ABC
-- | -- | --
Usuarios   Externos | Nombre Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Usuarios   Externos | Nombre Usuario | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Usuarios   Externos | Apellido Usuario | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Usuarios   Externos | Email | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Usuarios   Externos | Estado | Checkbox: habilitado   / No habilitado

</body>

</html>

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok

**Comment by ManeAlessandri** [comment]
Me retracto en cierre, la mayoria de los campos son de seleccion multiple y no esta funcionando, me deja seleccionar más de 1 pero la tabla me la entrega en blanco. Al menos en campos de Usuarios Interno: Nombre, Apellido, Email no funciona. Si funciona en Perfil.
Por favor corregir y revisar todos los campos de Usuarios Externos


![Image](https://user-images.githubusercontent.com/110253850/183700345-f40ff754-8dc5-4971-80cf-b65ea718de92.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
