### ISSUE TITLE
Ver Cuenta Corriente: Tabla de definciones (ERS 3.2.6.1): Falta Columna Rut Proveedor

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#24]
En definición de columnas el primer campo debe ser "RUT Proveedor", esto solo para perfiles Admin y Pago Prveedor. No aporta en caso de Proveedor.

![Image](https://user-images.githubusercontent.com/110253850/182914661-eaabbd83-ca61-425b-ac17-a85a6c9bddcf.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok, en los 3 perfiles (proveedor no debe ver esta columna y esta ok)
