### ISSUE TITLE
OK PROD 2 Ver Pagos: filtros tabla de datos, corregir formatos de filtros (ERS 3.2.5.1) - Problema con filtro fechas y montos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#25]
RUT: no está en formato, y no está en orden (menor a mayor)
Proveedor: corregir a orden ABC
Obra: Búsqueda literal con 4 numeros, se puede dejar con contiene? Y poner lista desplegable con opcion multiple (como proveedor)
Nombre Obra: Dejar ABC, lista desplegable y seleccion multiple
Fecha Pago: ok con seleccion exacta, filtro esta arriba
Monto: Se puede dejar con opción de rango de montos a elegir. esta con busqueda exacta sin puntos
Modalidad de Pagos: falta orden ABC
Lote: dejar búsqueda con contiene, está exacta

Búsquedas deben quedar así:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA
-- | --
Rut | Búsqueda en formato   con puntos y -, lista desplegable ABC
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Obra | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Nombre Obra | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Fecha de Pago | Selecion exacta   (apoyo de rangos con busqueda superior)
Monto | Busqueda contiene y   no exacta y con opcion de rangos
Modalidad de   Pagos | Lista deplegable ABC,   selección multiple y contiene (no exacto)
Lote | Busqueda contiene y   no exacta

</body>

</html>

**Comment by ManeAlessandri** [comment]
Campos en su mayoria corregidos, excepto:
Monto: búsqueda contiene y no tiene opción por rangos

**Comment by ManeAlessandri** [comment]
Pendiente a Todo 2

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Fecha de Pago:
1) Rango introducido no se borra al limpiar con boton de filtro y general, si se limpian datos de tabla, pero sigue escrito rango de fechas (PRIORITARIO)
2) Si se quiere elegir un día exacto, no basta con presionar el día, se debe presionar 2 veces y no avisa que debe ser asi o se debe introducir rango (no prioritario)

Monto: "mayor que" busca "mayor o igual", corregir nombre de búsqueda (que diga "mayor o igual" o que busque "mayor que" realmente) . Lo mismo para menor que. No Prioritario

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
