### ISSUE TITLE
OK PROD 1 Ver Pagos: problemas varios al buscar por Proveedor(filtros superiores no de tabla)  (ERS 3.2.5.1): Nombre y RUT

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#26]
**Problema 1:** Al buscar Proveedor por Rut, lista desplegable aparece con formato RUT (puntos y guiones), pero luego de Buscar, el Rut queda sin formato

![Image](https://user-images.githubusercontent.com/110253850/182883924-91dc135e-544b-425f-82dc-60305cc881ee.png)

![Image](https://user-images.githubusercontent.com/110253850/182883777-8bcbb0d0-15a6-4271-994c-00b58f9bbc55.png)

**Problema 2:** Lista desplegable de búsqueda por RUT aparece con Puntuación, pero si uno busca escribiendo con puntos y guión no reconoce los RUT, reconoce solo si se escriben solo números--> Por favor unificar a formato con puntuación

![Image](https://user-images.githubusercontent.com/110253850/182886513-a18c9d82-83e9-421d-8bde-363ed95eed7c.png)

![Image](https://user-images.githubusercontent.com/110253850/182886715-23b60244-9f7e-4f3f-b42e-8d828928fc8e.png)

**Problema 3:** Lista que se despliega en búsqueda de Rut, no está ordenada de menor a mayor

![Image](https://user-images.githubusercontent.com/110253850/182887148-cf6e8eea-3735-4af2-b027-ffbc6e376517.png)

**Problema 4:** Búsqueda por nombre está textual y debe ser exige desde el inicio, busqueda debiera ser "tipo contiene". Ejemplo, en lista aparece PERI CHILE LTDA., busco por Chile hy aparece solo CHILEMAQ S.A.
![Image](https://user-images.githubusercontent.com/110253850/182889977-d1d27230-79f8-4914-ad57-36f208ce86c1.png)

Pero si busco "Per" se despliega:

![Image](https://user-images.githubusercontent.com/110253850/182890139-4f20d979-7a06-466d-825c-057c2650f8cd.png)

**Comment by ManeAlessandri** [comment]
1 Urgente.

1) Error de Rut, no busca correctamente (ejemplo RUT 77.730.720-7 no aparece en busqueda):


![Image](https://user-images.githubusercontent.com/110253850/185951790-993261c2-86be-485a-aeb2-fe3d1c12acea.png)

2) Problema: puntuación RUT, dijimos lo dejaríamos asi por la dificultad de resolverlos

3) Lista desplegable ABC: esta resuelto

4)  Resuelto

**Comment by matiaskatsh** [comment]
Probar en Productivo

**Comment by Ditassara** [comment]
Probado en QA y punto 1 sigue pasando lo mismo. Traté de buscar el RUT 77.398.220-1 y no aparece en el buscador.



![Image](https://user-images.githubusercontent.com/56659426/188020945-1c273737-f228-40ef-9a2e-d0acbaab743a.png)

**Comment by Ditassara** [comment]
Revisado en Productivo, por el mismo RUT 77.398.220-1 y en el filtro no aparece, se consulta a Matias y me aclara que el Rut buscado no aparece en base de datos. 
Adjunto evidencia.

![image](https://user-images.githubusercontent.com/56659426/188150687-bc3e8c86-0f4c-4251-90ce-817a01b3be9d.png)
![image](https://user-images.githubusercontent.com/56659426/188150720-a80201ec-f04f-44d7-b48d-7c6cb7de0ac7.png)

**Comment by ManeAlessandri** [comment]
ok lo estamos revisando internamente

**Comment by ManeAlessandri** [comment]
Esto queda resuelto con lista de proveedores (25.000) donde se indican los activos de los ultimos 24 meses)
