### ISSUE TITLE
Desde Módulo Usuario: No permite Crear Nuevo Usuario Externo (proveedor) (ERS 3.2.4.4) - Ahora problema Mensajes

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#29]
No me permite crear un nuevo Usuario Externo (Proveedor), arroja error de "Prestador no Registrado", que RUT no se encuentra en Sistema, a pesar de que proveedor está en la lista de Módulo "Gestionar Proveedores"

Según ERS, los proveedores podían solicitar la creación de su cuenta, desde la página de Inicio, o bien admin/Pago Proveedores de Ingevec podían crear los usuarios desde el Módulo Usuario Externo.

Hice la prueba con 2 RUT de proveedor distintos:
RUT 88.962.100-1

![Image](https://user-images.githubusercontent.com/110253850/182698476-04ad9034-832c-4bcf-a785-d05c9aa37a5b.png)

![Image](https://user-images.githubusercontent.com/110253850/182698491-7bb618c3-2f3e-429d-b263-e16810bc25b3.png)

RUT 76.005.814-9

![Image](https://user-images.githubusercontent.com/110253850/182698536-d457f48b-3ad0-4f36-8749-e2d280f9d3a1.png)

![Image](https://user-images.githubusercontent.com/110253850/182698555-98e55c6a-2fb0-4240-96c0-6d2d8e3913aa.png)

Lista de Módulo Gestionar  Proveedores, donde se muestra que los 2 RUT existen

![Image](https://user-images.githubusercontent.com/110253850/182698502-8f2c5deb-32a0-4f12-a656-04238989c331.png)

**Comment by ManeAlessandri** [comment]
Funciona, pero arroja una serie de mensajes que no aplican (solo "Usuario Creado" está OK)


![Image](https://user-images.githubusercontent.com/110253850/183666896-ab41b88b-ca5c-419c-b544-39cfee614a2d.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
