### ISSUE TITLE
Reestablacer Contraseña / Mail no existe: No arroja error correcto (ERS 3.2.2.2 Exc 1.1)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#30]
Error no hace referencia a que mail no existe. 

![Image](https://user-images.githubusercontent.com/110253850/182465296-dac1789c-2c04-4e0a-8608-2b05efdf545a.png)

**Comment by cbastiasv** [comment]
El error que arroja firebase al ingresar ese correo es que el formato del email no es correcto. Se cambio el mensaje para que señale eso. Firebase no considera que no existe sino que considera que está mal escrito

**Comment by ManeAlessandri** [comment]
ok
