### ISSUE TITLE
OK PROD Cuenta Corriente: error en búsqueda con facturas pagadas PDTE #129 y 148

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#31]
En busqueda, de periodo 01/07/2022 hasta 04/08/2022 arroja 3361 registros. Pero cuando hago la misma busqueda, pero esta vez marco el Checkbox de Incluir facturas Pagadas, lo que debiera dar una mayor cantidad de registros, me arroja 1711

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
En búsqueda, de periodo 01/07/2022 hasta 04/08/2022 arroja 3361 registros -> Se mantiene como antes
Al agregar facturas pagadas me entrega la misma cantidad 3361 (antes entrega 1711)

Misma busqueda: del 01/01/2022 al 31/01/2022, sin ningun otro campo --> Arroja 1678 registros
Incluyo facturas Pagadas --> 1678 Registros: se mantiene la cantidad

Este check box de facturas pagadas no está funcionando (lista Cta Cte debe venir sin facturas pagadas, las que aparecen solo si uno marca el check box y hace la busqueda), o la regla interna que tenia que crear para identificar facturas pagadas no está funcionando bien

**Comment by ManeAlessandri** [comment]
cómo identifico cuales son los documentos pagados?? Necesito ticket 129 resuelto

**Comment by ManeAlessandri** [comment]
PDTE Ticket 148

**Comment by ManeAlessandri** [comment]
ok
