### ISSUE TITLE
Cuenta Corriente: Búsqueda de facturas con NC PDTE #129

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#32]
En búsqueda, de periodo 01/07/2022 hasta 04/08/2022 arroja 3361 registros, sin ningún otro filtro de búsqueda. Pero cuando hago la misma búsqueda, pero esta vez marco el Checkbox de "Solo facturas con NC", lo que debiera dar unos pocos registros porque son solo las fcaturas con NC, me arroja los mismo registros de antes 3361

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Error contibua, con filtro de facturas con NC y sin sigue arrojando la misma cantidad de documentos, no se si es problema que la regla está mala (Documentos con campo "NC Solicitada"  es distinto de vacio) o si no está hecha

**Comment by ManeAlessandri** [comment]
No tengo como chequear que sean documentos con NC. Necesito ticket 129 resuelto)

**Comment by ManeAlessandri** [comment]
Problema persiste: Documentos con NC, debe mostrar solo esos, y son todo aquel documento donde el campo "NC solicitada" sea distinto de "" o distinto de "0". Esto lo estoy confirmando internamente en Ingevec, por favor no corregir aun

**Comment by ManeAlessandri** [comment]
CONFIRMADO: Facturas con Nota de Credito, son aquellas con campo NC<>0. Verificar regla, porque no esta funcionando correctamente:

Cuando se presione checkbox de facturas con NC, debe entregar SOLO facturas con NC, independiente de si está seleccionado boton de incluir facturas Pagadas. (los 2 checkbox son un "y")

Ejemplos


![Image](https://user-images.githubusercontent.com/110253850/187525487-e2a17189-9a9a-4093-a59b-69fba9c967ea.png)



![Image](https://user-images.githubusercontent.com/110253850/187525612-54012104-8a5a-4db4-a23d-759a4d592f56.png)

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
No me entrega las facturas con NC y que ademas tienen facturas pagadas (ie saldo $0), me tiene que entregar todas las con NC.

Ejemplo Sodimac desde 01/01/2022 a 13/09/2022 marco "solo facturas con NC" y me entrega 43 y cuando marco facturas pagadas me agrega 3 mas (46)

**Comment by ManeAlessandri** [comment]
se reabre

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
