### ISSUE TITLE
Cuenta Corriente: Descarga de Excel

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#33]
Excel se puede descargar pero hay error en columna **Nombre Obra** (del Portal), en Excel se llama "Descripcion Obra" y el campo viene casi vacio, salvo excepciones que no corresponden a nombre obra y **Campo fecha** viene en blanco.

![Image](https://user-images.githubusercontent.com/110253850/182936325-9b9f6618-b024-4bd0-b835-c606b3c2709b.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
