### ISSUE TITLE
Inicio: Documentos para Pronto Pago: Error en nombre de campo Descripción DP Pronto Pago

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#35]
En Inicio de proveedores en tabla pronto pago dice campo Descripción y debiera ser "Nombre Obra", por favor corregir

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
No tengo casos de proveedores pronto pago para poder visualizar

**Comment by ManeAlessandri** [comment]
ok
