### ISSUE TITLE
Cuenta Corriente: Búsqueda superior por "Estado Factura" se queda pegado

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#36]
Busqueda por estado de factura se queda pegado, al intentar desplegar opciones de búsqueda (puede ser porque campo de tabla se llama solamente "Estado"

![Image](https://user-images.githubusercontent.com/110253850/182930525-3674dbbf-e986-4529-a553-7bd1d351ee5e.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
