### ISSUE TITLE
Buscar rango de fechas en Estadísticas Portal

### ISSUE THREAD

**Issue by Ditassara** [matiaskatsh/front_integracion#4]
Al buscar por rango de fechas, deja seleccionar un rango superior a los 6 meses como se pide en la ERS.

![Image](https://user-images.githubusercontent.com/56659426/179099495-e7a40307-74c1-4d51-a73a-71b54012a8da.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok,  no se puede cerrar ticket, no aparece boton
