### ISSUE TITLE
Órdenes de Compra: corregir título de campo "Número de Obra" en Tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#41]
En todas las demás tablas del Portal el Campo "Número de Obra" se llama "Obra". Dejar como "Obra" en esta tabla también

![Image](https://user-images.githubusercontent.com/110253850/182975128-d7f58e6f-74de-49be-ad31-9e0070bf19cc.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
