### ISSUE TITLE
1 Tickets: formulario de creación de Tickets, permite cancelar la creación pero al abrir un nuevo ticket los campos siguen completados --> Genera problema de alertas

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#43]
Al cancelar y volver a entrar a ticket, se mantienen los datos anotados en formulario, esto ocurre mientras uno se mantenga en el módulo de tickets, si me cambio a otro modulo y vuelvo a tickets se borran. Se deben borrar siempre.

![Image](https://user-images.githubusercontent.com/110253850/183087519-489d53f6-f05e-466c-bc33-ab287da2a9f9.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
OK problema anterior se resolvió, pero se genero otro

Hay un error que me imagino es a raiz de la correción de este ticket, cuando accedo a un nuevo ticket y elijo "Tipo de Solicitud" "Factura Rechzada" (pasa con los otros tambien) me arroja alerta de campo obligatorio y no me completa el campo como lo seleccioné a la segunda vez me lo deja:


![Image](https://user-images.githubusercontent.com/110253850/183736847-64b36c34-7d6c-49ca-9a2d-4298e3a23b56.png)

**Comment by ManeAlessandri** [comment]
1 Urgente

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
