### ISSUE TITLE
Tickets: Tablas de Pronto Pago (Proveedor y perfiles Ingevec): campo ID Solicitud debe ser "ID Ticket"

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#45]
Estandarizar nombre de Campo "ID Solictud" a "ID Ticket" Igual que en tablas de Tickets Abiertos y Cerrados

![Image](https://user-images.githubusercontent.com/110253850/183101830-e87d85c5-486c-46c4-82fc-a0ba56fabd36.png)

![Image](https://user-images.githubusercontent.com/110253850/183101902-58a1b4a1-97e2-469c-848b-538235fcf590.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
