### ISSUE TITLE
OK PROD 2 Tickets Activos: perfiles Ingevec: corregir formato de filtros de tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#46]
En usuarios INGEVEC, módulo Tickets, Pantalla "Activos"  Filtros deben quedar de la siguiente manera:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA | COMENTARIO
-- | -- | --
Nivel Criticidad | Lista deplegable y   sin busqueda (solo selección) | Opciones Alto / Medio / Estándar
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto) |  
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos |  
Fecha Último Mensaje | Seleccion exacta,   Idealmente que permita selección por rangos |  
Fecha Estimada Respuesta | Seleccion exacta,   Idealmente que permita selección por rangos |  
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Tipo Solicitud | Lista deplegable y   sin busqueda (solo selección) |  
Asunto | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Estado | Lista deplegable y   sin busqueda (solo selección) |  

</body>

</html>

**Comment by matiaskatsh** [comment]
Resuelto (falta rango de fecha)

**Comment by ManeAlessandri** [comment]
No está al 100%:
- Revisar todos los filtros que debieran estar ordenados por ABC.
- Rango de fecha pendiente (en este caso no hay búsqueda de cabecera que me pudiera ayudar a resolverlo)

**Comment by Ditassara** [comment]
Esto según ERS no estaría considerado y la prioridad actualmente es pasar al productivo, por lo tanto quedaría como mejora a futuro y considerado un adicional.

**Comment by ManeAlessandri** [comment]
ok, lo unico pendiente es el rango de fechas. Se vuelve a Todo 2

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Problema con filtro fecha: no se borra lo anotado (si devuelve tabla completa) PRIORITARIO y rango de fechas no avisa que es un rango (esto ultimo no es prioritario), si 1 quiere 1 dias exacto hay que apretar 2 veces el dia

Si uno filtra en fecha creacion, en fechaultimo mensaje queda anotado el rango en la busqueda (mal), pero no filtrado (ok no deberia filtrar)). Lo mismo pasa para fecha estimada de respuesta,

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
