### ISSUE TITLE
Tickets Cerrados: perfiles Ingevec: corregir formato de filtros de tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#47]
En usuarios INGEVEC, módulo Tickets, Pantalla "Cerrados"  Filtros deben quedar de la siguiente manera:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA | COMENTARIO
-- | -- | --
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto) |  
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos |  
Fecha de Cierre | Seleccion exacta,   Idealmente que permita selección por rangos |  
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Tipo Solicitud | Lista deplegable y   sin busqueda (solo selección) |  
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Cerrado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  

</body>

</html>

**Comment by Ditassara** [comment]
Esto según ERS no estaría considerado y la prioridad actualmente es pasar al productivo, por lo tanto quedaría como mejora a futuro y considerado un adicional.

**Comment by ManeAlessandri** [comment]
Resuelto excepto rangos de fechas (pero aca no es necesario, porque hay varios campos de fechas.Esto segun reunion 19/08
