### ISSUE TITLE
2 Tickets Pronto Pago: perfiles Ingevec: corregir formato de filtros de tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#48]
En usuarios INGEVEC, módulo Tickets, Pantalla "Pronto Pago"  Filtros deben quedar de la siguiente manera:
NOTA: Estado no está ni con filtro ni con orden (agregar ambos)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA | COMENTARIO
-- | -- | --
Nivel Criticidad | Lista deplegable y   sin busqueda (solo selección) |  
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto) | *Tabla dice ID Solicitud, pero se pidió cambiar a ID Ticket
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos |  
Rut Proveedor | Búsqueda en formato   con puntos y -, lista desplegable ABC |  
Proveedor | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Estado | Lista deplegable y   sin busqueda (solo selección) |  

</body>

</html>

**Comment by ManeAlessandri** [comment]
Pdte: --> se devuelve a Todo 2
ID Ticket: Orden ABC (de lista desplegable)
Rut Provedor (no lo puedo chequear, porque solo rut 1-9 tiene tickets)
Provedor (no lo puedo chequear, porque solo rut 1-9 tiene tickets) --> NOTA algunos proveedores estan en blanco a pesar de tener todos los mismo rut
Creado POr: igual que Proveedor

**Comment by matiaskatsh** [comment]
pdte fecha

**Comment by matiaskatsh** [comment]
resuelto

**Comment by ManeAlessandri** [comment]
Problema en:
1) Criticidad, Estándar en filtro está con tilde, pero en registros está sin tilde. Problema **probablemente se repetirá en Tickets abiertos y en Cerrados** (en estos últimos 2 casos, todos los tickets son nivel medio). Corregir en todos
2) ID Ticket: al abrir filtro dice "Gestionado Por" corregir. Además apaarecen los números de tickets correctamente, pero al elegir uno para filtrar la tabla queda en blanco (puede ser por los 000 iniciales del ticket). Corregir

Todo el resto está OK

**Comment by ManeAlessandri** [comment]
ok
