### ISSUE TITLE
Tickets Activos: perfiles Proveedor: corregir formato de filtros de tabla

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#49]
En usuarios Proveedor, módulo Tickets, Pantalla "Activos"  Filtros deben quedar de la siguiente manera:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA | COMENTARIO
-- | -- | --
ID Ticket | Lista deplegable   Menor a Mayor, selección multiple y contiene (no exacto) |  
Fecha de Creación | Seleccion exacta,   Idealmente que permita selección por rangos | *Portal dice fecha y Hora, pero se pidio dejar en Fecha
Fecha Último Mensaje | Seleccion exacta,   Idealmente que permita selección por rangos | *Portal dice fecha y Hora, pero se pidio dejar en Fecha
Asunto | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Creado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Gestionado Por | Lista deplegable ABC,   selección multiple y contiene (no exacto) |  
Estado | Lista deplegable y   sin busqueda (solo selección) |  

</body>

</html>

**Comment by matiaskatsh** [comment]
Resuelto (falta rango de fecha)

**Comment by ManeAlessandri** [comment]
No está al 100%:

Revisar todos los filtros que debieran estar ordenados por ABC.
Rango de fecha pendiente (en este caso no hay búsqueda de cabecera que me pudiera ayudar a resolverlo)

**Comment by Ditassara** [comment]
Esto según ERS no estaría considerado y la prioridad actualmente es pasar al productivo, por lo tanto quedaría como mejora a futuro y considerado un adicional.

**Comment by ManeAlessandri** [comment]
Todo resuleto menos rango de fechas, pero en este caso (a diferencia de Pronto Pago) como tiene mas campos de fechas, se puede dejar busqueda exacta y sin rango (conversado en reunion viernes 19/08)
