### ISSUE TITLE
Visualización de un Ticket: completar campos faltantes y formato

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#52]
De acuerdo a ERS 3.2.9.3, falta que aparezca en ticket 
1) Nombre Proveedor (solo Ingevec) 
2) Creado por (todos los pefiles). 
3) Corregir formato monto (Ingevec) --> $19.990 (ejemplo)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
