### ISSUE TITLE
Visualización de un Ticket: ver número de documento desde donde se creó el ticket

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#53]
En ERS 3.2.9.3 dice "Para los casos en que el ticket hubiera sido creado a partir de una factura u orden de compra, en los datos a mostrar en el detalle figurará el número identificador del documento correspondiente, visible para todos los perfiles (Administrador, Pago Proveedor y Proveedor)"

Este número se debiera ver en visualización de mensajes, y no ocurre en ninguno de los perfiles. Solo cuando el proveedor crea el ticket desde un documento, el numero del documento aparece en el encabeza, pero despues ya no se visualiza

![Image](https://user-images.githubusercontent.com/110253850/183111981-fc5cf3e7-5b9b-4a6c-bcdd-a7825318c412.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Resuelto
