### ISSUE TITLE
1 Cambios de Estados en Ticket: Cambio de estados automaticos no están todos resueltos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#54]
En ERS 3.2.9.5 en tabla inicial de definiciones dice:

El sistema cambiará automáticamente de estado cuando:
-	A un ticket en Estado Ingresado sea agregado el primer Mensaje por parte de un usuario Ingevec. En estos casos el ticket pasará a estar En Revisión. --> **No está ocurriendo, validar que el cambio de estado automatico sea solo con un mensaje de Ingevec, y no con uno de Proveedor**
-	Se utilice la funcionalidad Solicitar Cierre del Ticket, donde el ticket pasará a estar en Estado Cierre Solicitado. --> **si esta resuelto**
-	El sistema cierre automáticamente un ticket que ha sido objeto de la funcionalidad Solicitar Cierre del Ticket, donde pasará a estar en Estado Cerrado. --> **Según ERS que ocurre en 5 días, pero yo creo que no está ocurriendo, dado que hay tickets de mediados de julio en estado Cierre Solicitado (no tengo como saber fecha de solicitud de cierre). Pero cuando miro los tickets cerrados, todos han sido por proveedor y ninguno por "Sistema"**
-	Un usuario Proveedor utilice la funcionalidad Cerrar Ticket, el que cambiará el Estado del ticket a Cerrado. --> **Está disponible opción, pero arroja mensaje en inglés --> Corregir** (el cierre si funciona ok)

![Image](https://user-images.githubusercontent.com/110253850/183130229-ce6f13d8-7142-42b5-9e48-29fdaaf2290a.png)

**Comment by cbastiasv** [comment]
Mensaje Resuelto

**Comment by ManeAlessandri** [comment]
y que paso con el resto del ticket?

**Comment by Ditassara** [comment]
Punto 1 ya no corre, al abrir el ticket cambia el estado automáticamente, y al mandar el mensaje se agrega el usuario que gestiona.
Punto 2 ok.
Punto 3 pendiente de que pasen 5 días hábiles para corroborar que esté funcionando.
Punto 4 ok.

**Comment by ManeAlessandri** [comment]
Punto 1) Ticket que pasa a estado "En Revisión" no queda con Gestionado por registrado, hasta que no mande un mensaje. Es decir, ni con adjunto, ni poniendo monto de documento queda usario gestionado por registrado. Este usuario debiera ser quien lo abre, en primera instancia cuando cambia de estado, porque si no nadie se hace cargo de ticket

Punto 3 (está en ticket 123

**Comment by matiaskatsh** [comment]
1 .- al abrir un ticket en estado Ingresado se asigna el usuario gestiona

**Comment by Ditassara** [comment]
Punto 1 ok. 
Punto 3 en espera, se verá a través de otra incidencia nº 123.

**Comment by ManeAlessandri** [comment]
ok, resuelto punto 1,, el 3 queda en ticket 123
