### ISSUE TITLE
Solicitar Cierre de Ticket: al presionar boton debiera mandar mensaje de confirmación y no lo está haciendo - Resuelto parcialmente

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#55]
El cambio de estado se hace inmeadito sin mensaje de confirmación

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Mensaje no sigue formato del portal, es muy grande con letra chica, y mensaje muy extenso y alargado. Debiera ser de este tamaño:


![Image](https://user-images.githubusercontent.com/110253850/184214385-6827ad4d-2e5d-4110-92f4-251ead894283.png)



Dejar Mensaje: "¿Seguro que quiere Solicitar Cierre de Ticket? Si Proveedor no lo cierra, se hará automáticamente luego de 5 días hábiles"

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
