### ISSUE TITLE
Creación de ticket con mensaje en blanco

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#56]
Permite crear un ticket con un mensaje en blanco al colocar un " " (espacio); el campo no está vacío pero el mensaje no contiene nada.

![Image](https://user-images.githubusercontent.com/56659426/179237703-9a6699a1-3dda-4eee-aade-9a9cf3e96758.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
