### ISSUE TITLE
Editar Ticket y salir sin grabar: hay errores

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#57]
Al entrar a un ticket y escribir texto en mensaje, si se decide salir no hay un boton para cancelar, simplemente se debe apretar en la pantalla del portal fuera del ticket. 
Pero luego de eso si uno no se cambia de modulo, y entra a cualquier ticket (el mismo o distinto de antes) lo que uno escribio y no guardo sigue anotado sin importar al ticket que uno entre

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
