### ISSUE TITLE
Cierre Solicitado por Ingevec, Aprobación de Proveedor no está como en ERS 3.2.9.6

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#58]
Cierre solicitado no esta pidiendo a Proveedor aceptar o rechazar. Se ve ticket en estado "Cierre Solicitado" y al entrar al mensaje está la opción de cerrarlo, pero no de aceptar o rechazar cierre solicitado, y tampoco opcion campo para mensaje de por qué rechaza.

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
