### ISSUE TITLE
1 Tickets con archivos adjunto: varios problemas (Creación de tickets desde Módulo Tickets directamente)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#59]
En la creación de tickets desde Módulo Tickets directamente, me han surgido los siguientes problemas:
1) Subo adjuntos y no quedan guardados en ticket. Esto me paso con todo tipo de archivos en forma individual (PDF, WORD, PPT, JPG, PNG y Excel), en pantallazo se ve como si hubiera un archivo, pero no esta. También en grupo ocurre el problema

![Image](https://user-images.githubusercontent.com/110253850/183159654-b1b15027-810c-409d-86d3-d28a7ac85a99.png)

2) Muchos adjuntos: al crear un ticket con más de 5 adjuntos arroja error:

![Image](https://user-images.githubusercontent.com/110253850/183160701-bacd9297-1625-4d02-b4d3-dac0591676ef.png)

Pero mensaje de error se mantiene a pesar de que yo elimine archivos .

![Image](https://user-images.githubusercontent.com/110253850/183160785-f4ba52a8-c35b-48fd-92aa-8ae1d6cc7f3a.png)

Mensaje desaparece solo si presiono la cruz del mensaje

3) Muchos adjuntos: arroja error pero igual se puede crear con más de 5 archivos:

![Image](https://user-images.githubusercontent.com/110253850/183160996-60878e9b-64e9-4b07-94ea-16e188a26cbb.png)

Pongo Crear Ticket y me aparece creado:

![Image](https://user-images.githubusercontent.com/110253850/183161430-8b9164f7-7858-493c-842e-20a2ebf53c75.png)

Luego voy a ver el ticket (144): y me aparece como si tuviera los 6 archivos, pero no tiene ninguno cargado (mismo problma del punto 1) y además demuestra que no hace problema con 6 archivos:

![Image](https://user-images.githubusercontent.com/110253850/183164573-82c6926b-a885-4996-b97a-80265c977683.png)

![Image](https://user-images.githubusercontent.com/110253850/183164762-10acb446-6e13-46bc-9061-0addffdd13a2.png)

**Comment by cbastiasv** [comment]
Resuelto Ver Archivos Adjuntos

**Comment by matiaskatsh** [comment]
Resulto en los módulos tickets, inicio proveedor, ordenes de compra y cuenta corriente )

**Comment by ManeAlessandri** [comment]
1) ok
2) Muchos tickets: ya no aparece alerta, pero acabo de crear ticket 202, con 6 adjuntos, no me arrojo ningun tipo de alerta, me permitio guardar y cuando lo veo desde Proveedor está con 5 archivos (no se cual dejo fuera) y cuando miro desde ADMIN hay 4
Por favor **CORREGIR DE RAÍZ Y SOLUCIÓN DEFINITIVA AL TEMA DE LA CARGA DE ADJUNTOS**, entregando todas las alertas necesarias. Si son máximo 4 archivos, que no deje cargar mas de 4, con todas las alertas correspondientes. Si son hasta 4, pero al cargar uno nuevo el antiguo se borra, entonces alertarlo y preguntar si se está seguro... etc




![Image](https://user-images.githubusercontent.com/110253850/185216048-fa24cf94-94f6-4d5c-a76c-d4d09155c519.png)

**Comment by ManeAlessandri** [comment]
Problema persiste.
Ahora desde Administrador veo 6 archivos y desde porveedor veo 5 en mismo ticket 202.
Se suponia era un maximo de 4. por fevor revisar especificaciones de mensajes anteriores y resolver este caso

**Comment by Ditassara** [comment]
Los archivos se ven en todos los perfiles sin problema, la misma cantidad.
El límite falta definir si es por cantidad de archivos a subir o por cantidad de archivos a mostrar (en páginas).

**Comment by ManeAlessandri** [comment]
ok

**Comment by ManeAlessandri** [comment]
ok
