### ISSUE TITLE
OK PROD 2 Ticket en estado Ingresado: desde perfil Admin, me deja guardar mensajes, pero no me deja guardar archivo.

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#60]
Si se resuelve cambio automático de estado (IRequerimiento #54) desde "Ingresado" a "En Revisión" esto se resolvería en parte (lo del adjunto). Pero de todos modos en Ingresado no debiera permitir mensajes

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Problema persiste ticket 192 (tambien en 168, de ahi no segui revisando):


![Image](https://user-images.githubusercontent.com/110253850/186004551-67110c8e-160b-4482-8e8f-b1cc3c07ce71.png)

**Comment by ManeAlessandri** [comment]
lo dejo en 2 Todo, porque a pesar de estar en ERS no es relevante

**Comment by Ditassara** [comment]
Esto sigue igual, al entrar a un ticket en estado Ingresado, cambia el estado a En revisión, pero no deja adjuntar archivos y si enviar mensajes, y al momento de salir del ticket y entrar de nuevo si te deja adjuntar.

**Comment by ManeAlessandri** [comment]
Por favor corregir, no se puede adjuntar arxchivos ni siquiera una vez que uno escribe un mensaje, solo volviendo a salir

**Comment by Ditassara** [comment]
Resuelto.

**Comment by ManeAlessandri** [comment]
ok
