### ISSUE TITLE
PDTE PP Cuenta Corriente: Boton para "Ir a consultar documentos Pronto Pago" ERS 3.2.6.1 Protoripo 15 DP Pronto Pago PDTE #144

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#61]
Tabla con contiene boton que está en prototipo 15 ERS. Por favor incorporar

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
No tengo como identificar que proveedor está habilitado para Pronto Pago, estoy a la espera de Ticket 67, para chequear

**Comment by ManeAlessandri** [comment]
Boton no esta apareciendo, recuerdo que lo bloqueamos para bloquear Pronto Pago en Productivo. Ticket #144

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
