### ISSUE TITLE
PDTE PP Cuenta Corriente: columna "Solicitud de Pronto Pago" No está calculada DP Pronto Pago

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#62]
La columna debe ser calculada, en base a si proveedor esta habilitado como PP, y en conjunto, si tiene todos sus documentos pendientes de pago menores a 60 días (si tiene 1 solo con + de 60 días, no puede tener ningún documento habilitado). Este campo es un boolean.
Notar que proveedor sin opción de PP, ya sea por inhabilidad o por antigüedad de documentos, no puede tener visibilidad de ninguna de las opciones de PP (columna debe desaparecer y tabla en Inicio también)

Si además se requiriera un campo para identificar si el PP ya fue solicitado, habría que hacer otro. Pero PP solicitado (con ticket) inhabilita el campo anterior.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
NO está resuelto adjunto pantallazo, fijarse en las fechas (60 días máximo) a proveedor 1-9 cbastias@spsgroup.cl no le debiera aparecer columna pronto pago.

Es el unico proveedor que pude probar, los demas los tengo con problemas de contraseñas con problemas ticket 65

**Comment by ManeAlessandri** [comment]
No tengo como chequear que esté resuelto: 
1) Me faltan documentos/ proveedores habilitados para PP para poder probar.
2) A nivel de Admin, no hay ningun documento en los ultimos 6 meses que esté en un estado distitinto a "No solicitado". 
3) No me queda claro cuales serán las opciones de este campo "Solicitud de Pronto Pago": solicitado, no solicitado y "no disponible/en blanco"?
4) cuál es el cálculo que se está haciendo para resolver esta columna

**Comment by ManeAlessandri** [comment]
4. Carlos comenta en reunión del 17/08 a las 17:30 que campo de cada documento se calcula, en base a estado documento Aprobado, luego  si Proveedor esta habilitado como PP, y luego si tiene menos de 60 días ese documento. En caso, de que proveedor tenga algún documento aprobado con más de 60 días, estos se resuelve ocultando la tabla de inicio de PP al proveedor y ocultando la Columna en tabla Cta Cte

**Comment by ManeAlessandri** [comment]
No puedo probar Pronto Pago, no se por  qué con proveedor RUT 1-9, puedo ver documentos y todo lo de pronto Pago (Inicio), pero con proveedor 10978771-K no me esta dejando.... a pesar de que por registros de cuenta Cte debiera poder verlo...
Dejo Usuario pparga89@gmail.com Clave Ingevec2022
 
Ahora problema no me aparece con ese proveedor, pero tampoco logro encontrar 1 proveedor que tenga documentos disponibles para Pronto Pago y probar (los filtros de cta cte estan errados y no puedo buscar facil, y descarga de excel no viene con datos pronto pago) :(

**Comment by ManeAlessandri** [comment]
ok
