### ISSUE TITLE
Mensajes de Alerta o confirmación: en todo el portal, duran unos pocos segundos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#63]
Mensajes duran unos pocos segundos y a veces no se alcanzan a leer, especialmente cuando aparecen 2. Se puede alargar duración o bien que pida cerrarlos?

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
