### ISSUE TITLE
Contraseña Proveedor: proveedor pparga89@gmail.com, lo cree con cave "Ingevec2022" y me dice contraseña incorrecta

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#65]
Proveedor está habilitado, creado desde Creación Usuario Externo en perfil Administrador (segun mis registros) directamente con RUT 1-9, pero me arroja error de clave incorrecta. No sé en qué parte del proceso está el error. Nota: todos los usuarios que he creado sin importar el Perfil, tienen la misma clave Ingevec2022

Proveedor pparga90@gmail.com desde pag portal, tampoco me deja, dice contraseña incorrecta

![Image](https://user-images.githubusercontent.com/110253850/183688067-e04cae7b-02d0-4462-ab8d-39d890485843.png)

**Comment by matiaskatsh** [comment]
En el formulario de creación de usuario externo no se ingresa contraseña, esta es autogenerada

**Comment by matiaskatsh** [comment]
![Image](https://user-images.githubusercontent.com/74660636/183763062-a9f722bc-3256-4827-a457-dac0bc8b9fc7.PNG)

**Comment by ManeAlessandri** [comment]
ok, gracias
