### ISSUE TITLE
Tickets Pronto Pago: sin Rut Proveedor - Problema persiste con tickets del 10/08

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#66]
Me aparecen varios tickets Pronto Pago sin RUT Proveedor (17 de 22) que tampoco los puedo abrir desde perfil Admin

![Image](https://user-images.githubusercontent.com/110253850/183713913-2e5b796a-75aa-4f99-abf2-de26d3ad658c.png)

**Comment by matiaskatsh** [comment]
Revisado, los tickets no se pueden visualizar debido que fueron creados con un formato anterior al actual.

**Comment by ManeAlessandri** [comment]
Puede ser pero problema, tambien lo tengo por ejemplo en ticket 182 creado ayer 10/08/2022  y varios otros tickets dek mismo dia

**Comment by matiaskatsh** [comment]
El ticket numero 182 pertenece a los tickets de atención no pronto pago

**Comment by matiaskatsh** [comment]
![Image](https://user-images.githubusercontent.com/74660636/184213737-87e9a2f1-a8b2-46d8-a04c-a91ef94a0ba6.png)

**Comment by ManeAlessandri** [comment]
ok
