### ISSUE TITLE
Cuenta Corriente: Busqueda desde encabezado limite 6 meses y busqueda por estado

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#67]
**Necesito este ticket resuelto, para encontrar documentos pronto pago y hacer todas las pruebas del proceso**

1) Búsqueda en encabezado debe ser máximo de 6 meses, siempre y cuando solo se ingresen fecha, pero si se agrega otro campo, debe permitir más de 6 meses  y cuando ingreso "Estado" me lo está exigiendo.

![Image](https://user-images.githubusercontent.com/110253850/183724744-ac1364bf-414e-4495-afb8-4c88b44fd0bd.png)

2) Más aun o está buscando por "Estado"

![Image](https://user-images.githubusercontent.com/110253850/183724721-9acf7614-e0ea-48c7-ab28-540ef668b581.png)

**Comment by matiaskatsh** [comment]
Resuelta notificación, falta filtro

**Comment by ManeAlessandri** [comment]
los 2 problemas persisten, no se que fue lo que se resolvio

**Comment by ManeAlessandri** [comment]
ok
