### ISSUE TITLE
2 Pagos: Búsqueda y Limpiar filtros con error

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#69]
Al hacer búsqueda con fecha y luego presionar limpiar filtros, no se borran campos llenados en búsqueda de fecha. Pero si entrega tabla sin filtros (ver fecha de ultimo registro de tabla como prueba)

Por favor chequear y resolver este error de limpieza de filtro en todos los modulos de los 3 perfiles

![Image](https://user-images.githubusercontent.com/110253850/184008703-31cb6541-71e1-48e6-8d92-9fb611daa3a4.png)

**Comment by ManeAlessandri** [comment]
ok esta funcionando, pero al hacer prueba de cambio de fecha, me arrojó el siguiente mensaje, que no es necesario que aparezca, que no sigue el formato de colores de los demás mensajes y habla en días (180), cuando los demas mensajes hablan de 6 meses (fijarse en rango de fechas de la búsqueda:


![Image](https://user-images.githubusercontent.com/110253850/185243201-0b60658b-619f-47c3-a731-81b89f9fc148.png)

**Comment by ManeAlessandri** [comment]
Lo paso para aca, a urgente, porque hizo ruido en capacitacion

**Comment by ManeAlessandri** [comment]
aplica para todos los modulos o busquedas Ingevec, eliminar mensajes azules de info de este tema

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
