### ISSUE TITLE
Cuenta Corriente/ Ver Lote: Unificar nombres de campos

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#70]
Unificar nombres de Campos, dejar el que está en negrita:
**Tipo** = Tipo Documento (ver Lote)
**N° Documento** = N° factura (Cta Cte) y Numero Documento (Ver Lote)

Los demás campos ok

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
