### ISSUE TITLE
OK PROD 2 Ver Lote: corregir Filtros

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#71]
Dejar filtros de búsqueda en tabla de la siguiente manera:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/males/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CAMPO | FORMATO   BÚSQUEDA
-- | --
Lote | Busqueda contiene y no exacta
Fecha de Pago | Seleccion exacta   (apoyo de rangos con busqueda superior)
Monto | Busqueda contiene y   no exacta y con opcion de rangos
Tipo Documento | Lista deplegable ABC,   selección multiple y sin busqueda (solo selección)
Numero   Documento | Busqueda contiene y   no exacta (formato string, puede tener texto)
Fecha | Seleccion exacta   (apoyo de rangos con busqueda superior)
Fecha de   Ingreso | Seleccion exacta   (apoyo de rangos con busqueda superior)

</body>

</html>

**Comment by ManeAlessandri** [comment]
2 Todo

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
