### ISSUE TITLE
2 Descarga de Excel (ERS3.2.5.1) - En todos los modulos y pantallas está con problema

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#72]
La descarga de Excel funciona, pero descarga de acuerdo a la búsqueda superior y no a lo que está en tabla (filtros + búsqueda).

Es decir, si uno busca en tabla con filtros y quiere descargar solo eso, se descarga todo (lo buscado), y no lo filtrado.

Se podrá corregir a descarga de los que está en tabla con búsqueda y filtros incluidos?

**Comment by ManeAlessandri** [comment]
2 Todo --> Pendiente

**Comment by matiaskatsh** [comment]
pdte: campo pp en cuenta corriente

**Comment by ManeAlessandri** [comment]
OK Modulo Pagos, Ver detalle pagos,  Ordenes de Compra, Gestionar Proveedores, Tickets abiertos

NO resuelto en: Usuarios Internos, Usuarios Externos

No puedo probar: Cuenta Corriente (problema en filtros) y Tickets Cerrados y PP (tiene  1 solo)

**Comment by ManeAlessandri** [comment]
Hay varios Excel que vienen con las columnas en distinto orden que las tablas del portal, en especial, las de Tickets.

Los Excel de tickets (activos cerrados y pronto pago) se necesita que las columnas vengan en orden de la tabla, para poder hacer comparaciones, los excel de los demás módulos, no tienen tanta relevancia

**Comment by ManeAlessandri** [comment]
ok
