### ISSUE TITLE
OK PROD 1 Cuenta Corriente: Búsqueda en encabezado por N° de factura

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#73]
La busqueda esta como exacta y debiera ser contiene, ejemplo caso de factura 0004670, la encuentra solo si escribo exacto. 

El problema de esto podría estar en si busco una factura de 2 digitos, no se podra poner regla en que 2 o menos digitos busque excato y 3 o mas busque contiene?

**Comment by ManeAlessandri** [comment]
1 Urgente

**Comment by Ditassara** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok
