### ISSUE TITLE
1 General: para busquedas de cabecera por rango de fechas, sin otro campo de busqueda, debiera arrojar alerta de 6 meses

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#75]
Debiera arrojar mensaje de máximo 6 meses, perfiles  admin y pago proveedor, hoy arroja mensaje alerta que busqueda no puede superar 6 meses, **pero entrega tabla sin indicar que filtro** (entrega desde "fecha Hasta", 6 meses hacia atras). 

Entiendo que este limite no está puesto para los perfiles proveedor. Por favor confirmar.

**Comment by ManeAlessandri** [comment]
1) ok
2) Pdte: Entiendo que este limite no está puesto para los perfiles proveedor. Por favor confirmar.

**Comment by Ditassara** [comment]
Confirmar con Carlos.

**Comment by ManeAlessandri** [comment]
ok

**Comment by ManeAlessandri** [comment]
ok
