### ISSUE TITLE
1 Tickets: carga de adjuntos en tickets abiertos - está con problemas

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#78]
1) Tomo como ejemplo Ticket 170: cargue 3 archivos en creación, luego 1 mas desde ticket abierto como Proveedor y finalmente 1 mas como Admin. Pero en rol Proveedor (cbastias) me aparecen los 5 y en Rol Admin aparecen 4

2)Además no me arroja ningun mensaje de haber cargado adjunto, uno apreta el boton, elige archivo y se carga y punto --> poner mensaje

3) Archivo cargado viene sin fecha/hora ni responsable

Proveedor lo ve asi:

![Image](https://user-images.githubusercontent.com/110253850/184045470-29d47249-063e-48cb-8dcd-1689450d1654.png)

Admin lo ve asi:

![Image](https://user-images.githubusercontent.com/110253850/184045500-c74e1466-14af-4999-aca9-df27c2de4599.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by matiaskatsh** [comment]
falta metadata

**Comment by ManeAlessandri** [comment]
Puntos 2 y 3 resueltos

Punto 1: el problema persiste del ticket 170 persiste: proveedor ve 5 archivos adjuntos y admin ve solo 4

No se la que te refieres con falta de metadata...

**Comment by matiaskatsh** [comment]
Resuelto (metadata hace referencia al usuario y fecha del documento)

**Comment by ManeAlessandri** [comment]
Que pasó con el quinto documento? en el ticket 170 originalmente cargue 5 documentos, desde proveedor se veian los 5 y desde admin solo 4. Ahora se ven 4 y 4.... que paso con el quinto?

Probé cargando varios  documentos desde admin, me dice cargado y se refleja en listado de adjuntos, pero en caso de admin aparecen solo 4 documentos, y se borra el más antiguo (**quedando 4)**. En perfil, proveedores **aparecen 5**, pero tambien se borran los mas antiguos:

ADMIN:


![Image](https://user-images.githubusercontent.com/110253850/185206824-a637ed1c-266b-4153-baeb-d4f4f680d45c.png)


Proveedor:


![Image](https://user-images.githubusercontent.com/110253850/185206922-31c602b5-b85e-49be-8b99-e141cb0837b9.png)

**Comment by ManeAlessandri** [comment]
Ticket sin resolver es 3era vez que arreglo no esta hecho y llega a QA para revisión

**Comment by Ditassara** [comment]
Revisado con ticket 238 al cual se le agregaron distintos archivos, desde todos los perfiles y se muestran correctamente.
Da mensaje de confirmación cuando se sube un archivo.

![Image](https://user-images.githubusercontent.com/56659426/186504072-68e51e3e-0be4-481f-aaa2-ea60332be595.png)

**Comment by ManeAlessandri** [comment]
ok, probados con ticket 238 y 243
