### ISSUE TITLE
1 Ticket y Mensaje en feriado: no arroja mensaje a proveedor ERS3.2.9.13

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#79]
No arroja alerta de dia feriado, puse feriado hoy (ticket ingresado fuera de horario de atencion) . No avisa ni para mensaje de ticket ya creado ni para nuevo ticket

Adicional al feriado hice la prueba a las 20:35, por lo que si no era por feriado el mensaje debiera haber llegado por los limites de horario de atencion.

- Corregir problema en ambos caos (feriado y horario de atencion)

**Comment by ManeAlessandri** [comment]
1 Urgente: parte del ERS. No me permite probafr habilitacion/deshabilitacion de feriados

**Comment by Ditassara** [comment]
Da mensaje de fuera de horario de atención, pero no de feriado.

**Comment by matiaskatsh** [comment]
![Image](https://user-images.githubusercontent.com/74660636/186914653-6f5fa52d-22e5-4c47-8ce5-aa6b9315efdd.png)

**Comment by matiaskatsh** [comment]
![Image](https://user-images.githubusercontent.com/74660636/186914882-b69288c9-4070-4922-aca3-69f80b9d20dd.png)

**Comment by ManeAlessandri** [comment]
ok
