### ISSUE TITLE
Mensaje indicando falta de datos en campo obligatorio

### ISSUE THREAD

**Issue by Ditassara** [matiaskatsh/front_integracion#8]
Al crear un ticket de atención por orden de compra no entrega mensaje señalando que faltan datos obligatorios por completar.

![Image](https://user-images.githubusercontent.com/56659426/179236512-12c734c2-4407-43da-8b85-e4448f6a9d7f.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
ok, ahora se bloquea boton para crear ticket

**Comment by ManeAlessandri** [comment]
no me deja cerrar ticket
