### ISSUE TITLE
1 Mensaje de creación de Ticket: no está configurado y no contiene número de ticket segun ERS 3.2.9.13

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#81]
1) Mensaje Configurado dice "Hola" y está apareciendo otro automatico:
2) ERS 3.2.9.13 Dice que mensaje debe decir el número de ticket, y no lo está dando --> esto resolverlo solo si no es muy complicado.
Si los puntos 1 y 2 es más facil resolverlo con mensajes automaticos entonces hacerlo de esa manera

![Image](https://user-images.githubusercontent.com/110253850/184050098-13ae790e-4636-458e-ac1d-b28d0ef0cc78.png)

![Image](https://user-images.githubusercontent.com/110253850/184049963-75043fa7-23f7-477b-a4d2-385afee73ded.png)

**Comment by ManeAlessandri** [comment]
1 Urgente parte del ERS, me impide probar otras duncionalidades

**Comment by Ditassara** [comment]
Probado, si da mensaje con Hola y el número de ticket.

**Comment by ManeAlessandri** [comment]
ok
