### ISSUE TITLE
Modulo Estadisticas Portal: Gráficos por Estados: problemas en búsquedas (filtros)

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#83]
Se identifican 4 problemas:

1) Periodo: permite elegir rango, pero no tiene boton de aceptar (Hay que hacer click afuera)

![Image](https://user-images.githubusercontent.com/110253850/184052476-258af39f-439e-4248-a4be-58995a213ffd.png)

2) Criticidad: una vez elegida una no se puede desmarcar, y por ende no se puede buscar sin criticidad, a menos que se salga de modulo estadistica y vuelva a entrar.

3) Usuario: no es una lista de usuarios (pago Proveedor), estan todos los usuarios repetidos (imagino que 1 por cada ticket. Debe ser Lista deplegable ABC, selección multiple y contiene (no exacto)

4) No hay botón de botón de limpiar filtros, por favor agregar

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Quedó 1 detalle pendiente del punto 3: Orden ABC a lista desplegable

**Comment by Ditassara** [comment]
Faltaría filtro de usuario, debe ser con selección múltiple, actualmente solo permite seleccionar uno.

Esto según ERS no estaría considerado y la prioridad actualmente es pasar al productivo, por lo tanto quedaría como mejora a futuro y considerado un adicional.


![Image](https://user-images.githubusercontent.com/56659426/185695856-3286d861-28b4-42cd-bb0d-dabbbf8b13b1.png)

**Comment by ManeAlessandri** [comment]
ya esta resuelto, comentario anterior no aplica
