### ISSUE TITLE
Campo Proveedor: estandarizar nombre en todas las tablas

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#91]
Nombre Campo debe ser "Proveedor" en vez "Nombre Proveedor"

Corregir en tablas en que aperece "Nombre Proveedro": Usuarios Externos, En estadadisticas Tickets abiertos por criticidad (en cantidad y montos) , EN Inicio Tabla solicitud de creaciones de usuarios,

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Falto 1
 EN Inicio Tabla solicitud de creaciones de usuarios,

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
sigue sin resolverse:


![Image](https://user-images.githubusercontent.com/110253850/185205361-826e6538-d830-4ba4-b65b-17a86a8a04c4.png)

**Comment by ManeAlessandri** [comment]
ok
