### ISSUE TITLE
Tickets: Ver Tickets Pronto Pago ERS3.2.11.3: Usuarios en campo Gestionado por estan en blanco

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#94]
Probleama está en los 3 perfiles

![Image](https://user-images.githubusercontent.com/110253850/184173217-68819a35-6cb9-4cbf-a2eb-162baa1b36fd.png)

**Comment by matiaskatsh** [comment]
Resuelto

**Comment by ManeAlessandri** [comment]
Me aparecen muchos no aplica, por ejemplo:
-  Estado Cierre solicitado: alguien tiene que haber solicitado cierre o no?
  
 Acaso se asigna Gestor de ticket cuando alguien envía un mensaje? o cuando sube un adjunto? y eso no considera la solicitud de cierre?
Por favor especificar, cuando se asigna y gestor

**Comment by matiaskatsh** [comment]
Resuelto usuario gestor se asigna al momento de enviar el primer mensaje por parte de usuario ingevec
