### ISSUE TITLE
Ver detalle ticket: con problema a veces no puedo abrir los que estan en estado Ingresado ERS 3.2.11.4

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#97]
Al intentar ver algunos tickets, siempre los de estado ingresado, no me abre el boton ver ticket. Se queda como pegado hasta que otro ticket me abre y me devuelvo a ver el anterior, o me cambio de modulo

Me paso con el segundo que es el #00073, imagen (y me paso con varios mas):

![Image](https://user-images.githubusercontent.com/110253850/184190714-9ea0ad84-6e5f-4e12-929c-a0a22aa717cf.png)

**Comment by matiaskatsh** [comment]
Resuelto (se eliminaron ticket con formato antiguo)

**Comment by ManeAlessandri** [comment]
ok
