### ISSUE TITLE
Ver Detalle Ticket Pronto Pago: correccciones varias de acuerdo a ERS 3.2.11.4

### ISSUE THREAD

**Issue by ManeAlessandri** [matiaskatsh/front_integracion#99]
Como en ERS: 
1) donde dice "desglose Nota de Crédito" debiera estar en negrita
2) Cuando una factura sea exenta: debiera decir igual el IVA, como en las afectas, para que se note que es $0 (excnta). O decir documento exento
3) Fecha de Pago en negrita, y ojala fecha al lado de ttulo y no abajo
4) OBS: se debe completar automatico de acuerdo a ERS
5) Total (de NC): debe venir en negrita y mas grande (ERS)

**Comment by matiaskatsh** [comment]
Resulto todos menos punto 4 ¿a que se refiere con completado automático?

**Comment by ManeAlessandri** [comment]
No está al 100%:
1) OK
2) No aparece Neto. Debe decir Neto, IVA y Total: Donde si es exenta IVA debe ser $0.
3) Fecha de Pago como ERS (al lado de titulo "Fecha de Pago:")
4) OBS:  error mio, no es automatico: debe sugerir a usuario Pago Proveedor completar ahí al menos; #Factura a la que se asociaría la NC, Glosa que debe poner proveedor en NC y correo de Ingevec al que la deben hacer llegar. De prototipo 46:


![Image](https://user-images.githubusercontent.com/110253850/185209436-263478d2-ef13-456d-a286-15947821603c.png)

**Comment by Ditassara** [comment]
Queda pendiente nº4

**Comment by ManeAlessandri** [comment]
ok. independiente del punto 4 se cierra el ticket. Debido a que es un requisito extra, que se vera en ticket
